local consts = require "constants"
local gs = require "game_state"

function init(self)
	math.randomseed(os.time())
	self.timer = 1/gs.circle_spawn_frequency
end

function update(self, dt)
	if gs.state ~= GS_PLAYING then
		return
	end
	
	self.timer = self.timer - dt
	if self.timer <= 0 then
		self.timer = 1/gs.circle_spawn_frequency
		local p = go.get_position()
		p.x = math.random(consts.min_x, consts.max_x)
		factory.create("#factory", p)
	end
end