local score = 0

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	msg.post("@render:", "clear_color", { color = vmath.vector4(0.7, 0.7, 0.7, 0) } )
end

function on_message(self, message_id, message, sender)
	if message_id == hash("add_point") then
		score = score + 1
		msg.post("/gui#gui", "update_score", { score = score })
	end
end